---
- name: check if spamassassin is already installed.
  stat:
    path: /usr/bin/spamassassin
  register: spamassassin_installed

- name: update apt cache if spamassassin is not yet installed.
  apt:
    update_cache: yes
  when: spamassassin_installed.stat.exists == false

- name: ensure spamassassin is installed
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - spamassassin
    - spamc
    - libmail-dkim-perl

- name: ensure spamd group is present
  group:
    name: "{{ spamassassin_user }}"
    state: present

- name: ensure spamd user is present
  user:
    name: "{{ spamassassin_user }}"
    shell: /bin/false
    home: "{{ spamassassin_home_dir }}"
    groups: spamd
    append: yes

- name: ensure spamassassin's directories are present
  file:
    path: "{{ spamassassin_home_dir }}"
    owner: "{{ spamassassin_user }}"
    group: "{{ spamassassin_user }}"
    state: directory
  with_items:
    - "{{ spamassassin_home_dir }}"
    - "{{ spamassassin_bayes_path }}"

- name: ensure spamassassin config is latest
  template:
    src: default/spamassassin.j2
    dest: /etc/default/spamassassin
    owner: root
    group: root
    mode: 0644
  notify: restart spamassassin

- name: ensure spamassassin default rules file is latest
  template:
    src: spamassassin/local.cf.j2
    dest: /etc/spamassassin/local.cf
    owner: root
    group: root
    mode: 0644
  notify: restart spamassassin

- name: ensure spamassassin logrotate is latest
  template:
    src: logrotate.d/spamd.j2
    dest: /etc/logrotate.d/spamd
    owner: root
    group: root
    mode: 0644

- include: pyzor.yml
  when: spamassassin_pyzor_enabled

- include: monit.yml
  when: spamassassin_monit_enabled
